# Generated by Django 4.1.3 on 2022-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
