# Generated by Django 4.1.3 on 2022-11-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_section',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
